# Public Domain (-) 2011 The Togethr Authors.
# See the Togethr UNLICENSE file for details.

official-host: togethr.at
primary-hosts: togethr.at
primary-cert: /etc/live-server/primary.cert
primary-key: /etc/live-server/primary.key
secondary-hosts: *.togethr.at
secondary-cert: /etc/live-server/secondary.cert
secondary-key: /etc/live-server/secondary.key
error-dir: /etc/live-server/error
static-dir: /etc/live-server/www
cookie-key: /etc/live-server/cookie.key
acceptor-key: /etc/live-server/acceptor.key
enable-hsts: true
upstream-host: togethrat.appspot.com
upstream-port: 443
upstream-tls: true
log-rotate: hourly
no-console-log: true
extra-config: /etc/live-server/local.yaml
