# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

cert-file: /etc/liveserver/liveserver.cert
key-file: /etc/liveserver/liveserver.key
official-host: togethr.at
redis-conf: /etc/liveserver/redis.conf
enable-hsts: true
upstream-host: togethrat.appspot.com
upstream-port: 443
upstream-tls: true
log-rotate: hourly
no-console-log: true
