# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

cert-file: /etc/frontend/frontend.cert
key-file: /etc/frontend/frontend.key
official-host: togethr.at
enable-sensor: true
redis-conf: /etc/frontend/redis.conf
enable-hsts: true
gae-host: togethrat.appspot.com
gae-port: 443
gae-tls: true
log-rotate: hourly
no-console-log: true
