# Public Domain (-) 2011 The Ampify Authors.
# See the Ampify UNLICENSE file for details.

cert-file: /etc/togethr/frontend.cert
key-file: /etc/togethr/frontend.key
official-host: togethr.at
enable-hsts: true
gae-host: togethrat.appspot.com
gae-port: 443
gae-tls: true
log-rotate: hourly
no-console-log: true
