application: togethrat
version: 1
runtime: go
api_version: 3
default_expiration: "14d"

handlers:

- url: /.static/(.*\.(css|js))
  secure: always
  static_files: build/\1
  upload: build/(.*\.(css|js))

- url: /.static/gfx
  secure: always
  static_dir: build/gfx

- url: /.*
  secure: always
  script: _go_app
